[package]
name = "magnetar_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.33"
serde = { version = "1.0.217", features = ["derive"] }